x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:

  bgutil-ytdlp-pot-provider:
    image: brainicism/bgutil-ytdlp-pot-provider:latest
    container_name: bgutil-ytdlp-pot-provider
    restart: unless-stopped
    logging: *default-logging
    ports:
      - "127.0.0.1:4416:4416"

  hymns-bot-0:
    image: ghcr.io/a83986475/hymns-bot:latest
    container_name: hymns-bot-0
    restart: unless-stopped
    logging: *default-logging
    env_file: ./.env
    environment:
      - BOT_TOKEN=${BOT0_TOKEN}
      - BOT_ID=${BOT0_ID}
      - BOT_INDEX=0
      - TZ=Asia/Shanghai
    volumes:
      - .:/app
    ports:
      - "0.0.0.0:8080:8080"
    depends_on:
      - bgutil-ytdlp-pot-provider

  hymns-bot-1:
    image: ghcr.io/a83986475/hymns-bot:latest
    container_name: hymns-bot-1
    restart: unless-stopped
    logging: *default-logging
    env_file: ./.env
    environment:
      - BOT_TOKEN=${BOT1_TOKEN}
      - BOT_ID=${BOT1_ID}
      - BOT_INDEX=1
      - TZ=Asia/Shanghai
    volumes:
      - .:/app
    depends_on:
      - bgutil-ytdlp-pot-provider

  hymns-bot-2:
    image: ghcr.io/a83986475/hymns-bot:latest
    container_name: hymns-bot-2
    restart: unless-stopped
    logging: *default-logging
    env_file: ./.env
    environment:
      - BOT_TOKEN=${BOT2_TOKEN}
      - BOT_ID=${BOT2_ID}
      - BOT_INDEX=2
      - TZ=Asia/Shanghai
    volumes:
      - .:/app
    depends_on:
      - bgutil-ytdlp-pot-provider

  hymns-bot-3:
    image: ghcr.io/a83986475/hymns-bot:latest
    container_name: hymns-bot-3
    restart: unless-stopped
    logging: *default-logging
    env_file: ./.env
    environment:
      - BOT_TOKEN=${BOT3_TOKEN}
      - BOT_ID=${BOT3_ID}
      - BOT_INDEX=3
      - TZ=Asia/Shanghai
    volumes:
      - .:/app
    depends_on:
      - bgutil-ytdlp-pot-provider

  hymns-bot-4:
    image: ghcr.io/a83986475/hymns-bot:latest
    container_name: hymns-bot-4
    restart: unless-stopped
    logging: *default-logging
    env_file: ./.env
    environment:
      - BOT_TOKEN=${BOT4_TOKEN}
      - BOT_ID=${BOT4_ID}
      - BOT_INDEX=4
      - TZ=Asia/Shanghai
    volumes:
      - .:/app
    depends_on:
      - bgutil-ytdlp-pot-provider
